package encoder;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/**
 * @author Dilshodbek Akhmedov, Pay 11:15. 03/11/22
 */
public class MD5Test {

    public static void main(String[] args) throws NoSuchAlgorithmException {
        String s = "{\n" +
                "    \"driver_id\": \"000002\",\n" +
                "    \"oper_sum\": 10.00,\n" +
                "    \"oper_type\": \"receipt\",\n" +
                "    \"name\": \"Пополнение счета\",\n" +
                "    \"oper_time\": \"20221104102719\",\n" +
                "    \"comment\": \"Комментарий к операциfи\",\n" +
                "    \"account_kind\": 0\n" +
                "}";
        System.out.println("Your HashCode Generated by MD5 is: " + getMd5(s));
    }

//    public static String getMd5(String input) {
//        try {
//            // Static getInstance method is called with hashing MD5
//            MessageDigest md = MessageDigest.getInstance("MD5");
//
//            // digest() method is called to calculate message digest
//            // of an input digest() return array of byte
//            byte[] messageDigest = md.digest(input.getBytes());
//
//            // Convert byte array into sigNum representation
//            BigInteger no = new BigInteger(1, messageDigest);
//
//            // Convert message digest into hex value
//            StringBuilder hashText = new StringBuilder(no.toString(16));
//            while (hashText.length() < 32) {
//                hashText.insert(0, "0");
//            }
//            return hashText.toString();
//        } catch (NoSuchAlgorithmException e) {
//            throw new RuntimeException(e);
//        }
//    }


    public static String getMd5(String input) {
        try {
            // Static getInstance method is called with hashing MD5
            MessageDigest md = MessageDigest.getInstance("MD5");

            // digest() method is called to calculate message digest
            // of an input digest() return array of byte
            byte[] messageDigest = md.digest(input.getBytes());

            // Convert byte array into signum representation
            BigInteger no = new BigInteger(1, messageDigest);

            // Convert message digest into hex value
            StringBuilder hashtext = new StringBuilder(no.toString(16));
            while (hashtext.length() < 32) {
                hashtext.insert(0, "0");
            }
            return hashtext.toString();
        } // For specifying wrong message digest algorithms
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }


}
